src/Entity/Spectacle.php
<?php

namespace App\Entity;

use DateInterval;
use DateTimeInterface;
use DateTimeZone;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\SpectacleRepository")
 */
class Spectacle
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date;

    /**
     * @ORM\Column(type="integer")
     */
    private $price;

    /**
     * @ORM\Column(type="integer")
     */
    private $available_tickets;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Team", mappedBy="spectacle")
     */
    private $teams;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Team", inversedBy="spectacles")
     */
    private $team;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Ticket", mappedBy="spectacle")
     */
    private $tickets;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\User", mappedBy="spectacle")
     */
    private $users;

    public function __construct()
    {
        $this->teams = new ArrayCollection();
        $this->tickets = new ArrayCollection();
        $this->users = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(int $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getAvailableTickets(): ?int
    {
        return $this->available_tickets;
    }

    public function setAvailableTickets(int $available_tickets): self
    {
        $this->available_tickets = $available_tickets;

        return $this;
    }

    /**
     * @return Collection|Team[]
     */
    public function getTeams(): Collection
    {
        return $this->teams;
    }

    public function addTeam(Team $team): self
    {
        if (!$this->teams->contains($team)) {
            $this->teams[] = $team;
            $team->addSpectacle($this);
        }

        return $this;
    }

    public function removeTeam(Team $team): self
    {
        if ($this->teams->contains($team)) {
            $this->teams->removeElement($team);
            $team->removeSpectacle($this);
        }

        return $this;
    }

    public function getTeam(): ?Team
    {
        return $this->team;
    }

    public function setTeam(?Team $team): self
    {
        $this->team = $team;

        return $this;
    }

    /**
     * @return Collection|Ticket[]
     */
    public function getTickets(): Collection
    {
        return $this->tickets;
    }

    public function addTicket(Ticket $ticket): self
    {
        if (!$this->tickets->contains($ticket)) {
            $this->tickets[] = $ticket;
            $ticket->addSpectacle($this);
        }

        return $this;
    }

    public function removeTicket(Ticket $ticket): self
    {
        if ($this->tickets->contains($ticket)) {
            $this->tickets->removeElement($ticket);
            $ticket->removeSpectacle($this);
        }

        return $this;
    }

    /**
     * @return Collection|User[]
     */
    public function getUsers(): Collection
    {
        return $this->users;
    }

    public function addUser(User $user): self
    {
        if (!$this->users->contains($user)) {
            $this->users[] = $user;
            $user->setSpectacle($this);
        }

        return $this;
    }

    public function removeUser(User $user): self
    {
        if ($this->users->contains($user)) {
            $this->users->removeElement($user);
            // set the owning side to null (unless already changed)
            if ($user->getSpectacle() === $this) {
                $user->setSpectacle(null);
            }
        }

        return $this;
    }

    public function __toString() {
        return $this->name;
    }

}

src/Form/SpectacleType.php
<?php

namespace App\Form;

use App\Entity\Spectacle;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class SpectacleType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name')
            ->add('date')
            ->add('price')
            ->add('available_tickets')
            ->add('users')
            ->add('teams')
            ->add('team')
            ->add('tickets')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Spectacle::class,
        ]);
    }
}

src/Controller/SpectacleController.php
<?php

namespace App\Controller;

use App\Entity\Spectacle;
use App\Form\SpectacleType;
use App\Repository\SpectacleRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/spectacle")
 */
class SpectacleController extends AbstractController
{
    /**
     * @Route("/", name="spectacle_index", methods={"GET"})
     */
    public function index(SpectacleRepository $spectacleRepository): Response
    {
        return $this->render('spectacle/index.html.twig', [
            'spectacles' => $spectacleRepository->findAll(),
        ]);
    }

    /**
     * @Route("/list", name="spectacle_list", methods={"GET"})
     */
    public function listSpectacle(SpectacleRepository $spectacleRepository): Response
    {
        return $this->render('spectacle/list.html.twig', [
            'spectacles' => $spectacleRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="spectacle_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $spectacle = new Spectacle();
        $form = $this->createForm(SpectacleType::class, $spectacle);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($spectacle);
            $entityManager->flush();

            return $this->redirectToRoute('spectacle_index');
        }

        return $this->render('spectacle/new.html.twig', [
            'spectacle' => $spectacle,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="spectacle_show", methods={"GET"})
     */
    public function show(Spectacle $spectacle): Response
    {
        return $this->render('spectacle/show.html.twig', [
            'spectacle' => $spectacle,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="spectacle_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Spectacle $spectacle): Response
    {
        $form = $this->createForm(SpectacleType::class, $spectacle);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('spectacle_index');
        }

        return $this->render('spectacle/edit.html.twig', [
            'spectacle' => $spectacle,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="spectacle_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Spectacle $spectacle): Response
    {
        if ($this->isCsrfTokenValid('delete'.$spectacle->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($spectacle);
            $entityManager->flush();
        }

        return $this->redirectToRoute('spectacle_index');
    }
}

templates/spectacle/_delete_form.html.twig
<form method="post" action="{{ path('spectacle_delete', {'id': spectacle.id}) }}" onsubmit="return confirm('Etes-vous certain de vouloir supprimer cet élément ?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ spectacle.id) }}">
    <button class="btn btn-md btn-light">Supprimer</button>
</form>

templates/spectacle/_form.html.twig
<div class="text-table ">
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-md btn-light">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}
</div>

templates/spectacle/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Editer un spectacle{% endblock %}

{% block body %}
    <h1 class="titleH1">Editer un spectacle</h1>

    {{ include('spectacle/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('spectacle_index') }}"><button class="btn btn-md btn-light">Retour à la liste</button></a>

    {{ include('spectacle/_delete_form.html.twig') }}
{% endblock %}

templates/spectacle/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nos spectacles{% endblock %}

{% block body %}
    <h1 class="titleH1">Nos spectacles</h1>
    <a href="{{ path('spectacle_new') }}"><button class="btn btn-md btn-light">Ajouter un nouveau spectacle</button></a>
    <table class="table">
        <thead>
            <tr>
                <th>Nom du spectacle</th>
                <th>Date</th>
                <th>Tarif</th>
                <th>Billets disponibles</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for spectacle in spectacles %}
            <tr>
                <td>{{ spectacle.name }}</td>
                <td>{{ spectacle.date ? spectacle.date|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ spectacle.price }}€</td>
                <td>{{ spectacle.availableTickets }}</td>
                <td>
                    <a href="{{ path('spectacle_show', {'id': spectacle.id}) }}">Voir</a>
                    <a href="{{ path('spectacle_edit', {'id': spectacle.id}) }}">Editer</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

templates/spectacle/list.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nos spectacles{% endblock %}

{% block body %}
    <div class="team_container">
        <div class="card mb-4" style="max-width: 500px; height: 550px;">
            <div class="row no-gutters justify-content-center">
                <div class="col-md-8">
                    <img src="/images/affiche_papillon.jpg" class="card-img" alt="Le spectacle Papillon">
                </div>
                <div class="col-md-16">
                    <div class="card-body">
                        <h5 class="card-title">Le spectacle Papillon</h5>
                        <p class="card-text">Un spectacle unique où nos artistes acrobates mettent en lumière la beauté de la faune et la flore.</p>
                        <a href="#" class="btn btn-dark">Acheter des billets</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="card mb-4" style="max-width: 500px; height: 550px;">
            <div class="row no-gutters justify-content-center">
                <div class="col-md-8">
                    <img src="/images/affiche_avatar.jpg" class="card-img" alt="Le spectacle Avatar">
                </div>
                <div class="col-md-16">
                    <div class="card-body">
                        <h5 class="card-title">Le spectacle Avatar</h5>
                        <p class="card-text">L'univers du film Avatar retranscrit dans un spectacle son et lumière époustouflant.</p>
                        <a href="#" class="btn btn-dark">Acheter des billets</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/spectacle/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nouveau spectacle{% endblock %}

{% block body %}
    <h1>Ajouter un nouveau spectacle</h1>

    {{ include('spectacle/_form.html.twig') }}

    <a href="{{ path('spectacle_index') }}"><button class="btn btn-md btn-light">Retour à la liste</button></a>
{% endblock %}

templates/spectacle/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nos Spectacle{% endblock %}

{% block body %}
    <h1 class="titleH1">Spectacles</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ spectacle.id }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ spectacle.name }}</td>
            </tr>
            <tr>
                <th>Date</th>
                <td>{{ spectacle.date ? spectacle.date|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Price</th>
                <td>{{ spectacle.price }}</td>
            </tr>
            <tr>
                <th>Available_tickets</th>
                <td>{{ spectacle.availableTickets }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('spectacle_index') }}">back to list</a>

    <a href="{{ path('spectacle_edit', {'id': spectacle.id}) }}">edit</a>

    {{ include('spectacle/_delete_form.html.twig') }}
{% endblock %}