src/Entity/Ticket.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\TicketRepository")
 */
class Ticket
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $nb_tickets;

    /**
     * @ORM\Column(type="integer")
     */
    private $total_price;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="tickets")
     */
    private $user;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Spectacle", inversedBy="tickets")
     */
    private $spectacle;

    public function __construct()
    {
        $this->spectacle = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNbTickets(): ?int
    {
        return $this->nb_tickets;
    }

    public function setNbTickets(int $nb_tickets): self
    {
        $this->nb_tickets = $nb_tickets;

        return $this;
    }

    public function getTotalPrice(): ?int
    {
        return $this->total_price;
    }

    public function setTotalPrice(int $total_price): self
    {
        $this->total_price = $total_price;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return Collection|Spectacle[]
     */
    public function getSpectacle(): Collection
    {
        return $this->spectacle;
    }

    public function addSpectacle(Spectacle $spectacle): self
    {
        if (!$this->spectacle->contains($spectacle)) {
            $this->spectacle[] = $spectacle;
        }

        return $this;
    }

    public function removeSpectacle(Spectacle $spectacle): self
    {
        if ($this->spectacle->contains($spectacle)) {
            $this->spectacle->removeElement($spectacle);
        }

        return $this;
    }
}

src/Form/TicketType.php
<?php

namespace App\Form;

use App\Entity\Ticket;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class TicketType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('nb_tickets')
            ->add('total_price')
            ->add('user')
            ->add('spectacle')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Ticket::class,
        ]);
    }
}

src/Controller/TicketController.php
<?php

namespace App\Controller;

use App\Entity\Ticket;
use App\Form\TicketType;
use App\Repository\TicketRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/ticket")
 */
class TicketController extends AbstractController
{
    /**
     * @Route("/", name="ticket_index", methods={"GET"})
     */
    public function index(TicketRepository $ticketRepository): Response
    {
        return $this->render('ticket/index.html.twig', [
            'tickets' => $ticketRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="ticket_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $ticket = new Ticket();
        $form = $this->createForm(TicketType::class, $ticket);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($ticket);
            $entityManager->flush();

            return $this->redirectToRoute('ticket_index');
        }

        return $this->render('ticket/new.html.twig', [
            'ticket' => $ticket,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="ticket_show", methods={"GET"})
     */
    public function show(Ticket $ticket): Response
    {
        return $this->render('ticket/show.html.twig', [
            'ticket' => $ticket,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="ticket_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Ticket $ticket): Response
    {
        $form = $this->createForm(TicketType::class, $ticket);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('ticket_index');
        }

        return $this->render('ticket/edit.html.twig', [
            'ticket' => $ticket,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="ticket_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Ticket $ticket): Response
    {
        if ($this->isCsrfTokenValid('delete'.$ticket->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($ticket);
            $entityManager->flush();
        }

        return $this->redirectToRoute('ticket_index');
    }
}

templates/ticket/_delete_form.html.twig
<form method="post" action="{{ path('ticket_delete', {'id': ticket.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ ticket.id) }}">
    <button class="btn">Delete</button>
</form>

templates/ticket/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/ticket/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Ticket{% endblock %}

{% block body %}
    <h1>Edit Ticket</h1>

    {{ include('ticket/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('ticket_index') }}">back to list</a>

    {{ include('ticket/_delete_form.html.twig') }}
{% endblock %}

templates/ticket/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ticket index{% endblock %}

{% block body %}
    <h1>Ticket index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nb_tickets</th>
                <th>Total_price</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for ticket in tickets %}
            <tr>
                <td>{{ ticket.id }}</td>
                <td>{{ ticket.nbTickets }}</td>
                <td>{{ ticket.totalPrice }}</td>
                <td>
                    <a href="{{ path('ticket_show', {'id': ticket.id}) }}">show</a>
                    <a href="{{ path('ticket_edit', {'id': ticket.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('ticket_new') }}">Create new</a>
{% endblock %}

templates/ticket/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Ticket{% endblock %}

{% block body %}
    <h1>Create new Ticket</h1>

    {{ include('ticket/_form.html.twig') }}

    <a href="{{ path('ticket_index') }}">back to list</a>
{% endblock %}

templates/ticket/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ticket{% endblock %}

{% block body %}
    <h1>Ticket</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ ticket.id }}</td>
            </tr>
            <tr>
                <th>Nb_tickets</th>
                <td>{{ ticket.nbTickets }}</td>
            </tr>
            <tr>
                <th>Total_price</th>
                <td>{{ ticket.totalPrice }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('ticket_index') }}">back to list</a>

    <a href="{{ path('ticket_edit', {'id': ticket.id}) }}">edit</a>

    {{ include('ticket/_delete_form.html.twig') }}
{% endblock %}